# Generated by Django 4.0.3 on 2022-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.IntegerField(verbose_name='セッション番号')),
                ('name', models.CharField(max_length=255, verbose_name='あだ名')),
            ],
        ),
    ]
