# Generated by Django 4.0.3 on 2022-05-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeep', '0002_rename_session_session_session_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='あだ名')),
                ('created_date', models.DateField(verbose_name='作成日')),
                ('cost', models.IntegerField(default=0, verbose_name='値段')),
                ('category', models.CharField(max_length=255, verbose_name='タグ')),
                ('detail', models.CharField(max_length=255, verbose_name='商品名')),
            ],
        ),
    ]
